---
title: "piamValidation: ARIADNE"
date: "`r format(Sys.Date())`"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
params:
  mif: ""
  cfg: ""
  warning: false
  message: false
  figWidth: 8
---

```{r include=FALSE}
library(piamValidation)
library(knitr)
library(dplyr)
library(ggplot2)
library(ggthemes)
library(plotly)

knitr::opts_chunk$set(
  echo = FALSE,
  error = TRUE,
  message = params$message,
  warning = params$warning
)
```

## Import and Prepare Data

Loading data from:

```{r}
for (m in params$mif) cat(paste0(m, "\n"))
```

Using config:

`r params$cfg`

```{r, message = FALSE}
# Data Preparation
df <- validateScenarios(params$mif, params$cfg)
df <- appendTooltips(df)
```
## Validation

### Summary
```{r}
# find "critical == yes" data points, that are red/yellow
colors <- c(green  = "#008450",
            yellow = "#EFB700",
            red    = "#B81D13",
            grey   = "#808080")
dplyr::count(df, critical, check)
```


### Historisch - KSG

Vergleich zu

- Historischer Wert UBA (2020)
- KSG (2030)

Ab 10% Abweichung: gelb, ab 20% Abweichung: rot


```{r}
historic <- TRUE
m <- "relative"
d <- filter(df, metric == m, ref_scenario == "historical")

if (nrow(d) > 0) {
  vars <- unique(d$variable)
  plot_list <- htmltools::tagList()
    for (i in 1:length(vars)) {
      plot_list[[i]] <- validationHeatmap(d, vars[i], met = m, historic, compareModels = T)
    }
  plot_list
}
```


### Projektionsbericht 2024 - MMS

Comparison to MMS Scenario from Projektionsbericht 2024

source: https://www.umweltbundesamt.de/dokument/datenanhang-kernindikatoren-projektionsbericht-2024

```{r}
historic <- FALSE
m <- "relative"
d <- filter(df, metric == m, ref_scenario != "historical" | is.na(ref_scenario))

if (nrow(d) > 0) {
  vars <- unique(d$variable)
  plot_list <- htmltools::tagList()
    for (i in 1:length(vars)) {
      plot_list[[i]] <- validationHeatmap(d, vars[i], met = m, historic, compareModels = T)
    }
  plot_list
}
```
